before_script:
  - bundle exec rake test_app
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
env:
  - DB=mysql
  - DB=postgres
language: ruby
rvm:
  - 2.1.5
  - 2.2.3
  - 2.2.5
  - 2.3.1
sudo: false